language: node_js

node_js:
  - "node"

dist: trusty

sudo: required

addons:
  chrome: stable

install:
  - npm --version
  - npm i

script:
 - npm run test:ci
 - npm run build

cache:
  directories:
    - node_modules
